apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-auth-service-deployment
  namespace: oauth2-auth-service-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: oauth2-auth-service-app
  template:
    metadata:
      labels:
        app: oauth2-auth-service-app
    spec:
      containers:
        - name: oauth2-auth-service-container
          image: docker.io/gamepkw/oauth2-auth-service-image:latest
          ports:
            - containerPort: 8080
