apiVersion: v1
kind: Service
metadata:
  name: oauth2-auth-service-nodeport-service
  namespace: oauth2-auth-service-namespace
spec:
  type: NodePort
  selector:
    app: oauth2-auth-service-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
