port: 9090
logger-output-path: "../../logs.yaml"

oauthStateString: "gamepkw"
google:
  clientID: "515592365350-fef5525j3kdk1bgoqtbrt1nl4jnjg57d.apps.googleusercontent.com"
  clientSecret: "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"
  redirectURL: "http://localhost:3001/home"
  scopes-profile: "https://www.googleapis.com/auth/userinfo.profile"
  scopes-email: "https://www.googleapis.com/auth/userinfo.email"

facebook:
  appID: "940552110936939"
  appSecret: "43268ba4fb1189815853c5f1e91539f5"
  authURL: "https://graph.facebook.com/oauth/authorize"
  tokenURL: "https://graph.facebook.com/oauth/access_token"
  scopes: "https://www.googleapis.com/auth/userinfo.email"

github:
  clientID: "26a3ebc9548e5bb788c8"
  clientSecret: "dc866db101e6e24db518936a1ce4b9b19ff0da8e"
  redirectURL: "http://localhost:3001/home"
  scopes: "https://www.googleapis.com/auth/userinfo.email"
